# Generated by Django 5.2.15 on 2026-06-14 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kworks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwork',
            name='price_minor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='KworkFAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('kwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='kworks.kwork')),
            ],
            options={
                'verbose_name': 'Kwork FAQ',
                'verbose_name_plural': 'Kwork FAQs',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='KworkImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='kworks/images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('kwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kworks.kwork')),
            ],
            options={
                'verbose_name': 'Kwork Image',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='kworks.kwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'kwork'), name='unique_favorite_per_user')],
            },
        ),
    ]
