# Generated by Django 5.2.15 on 2026-06-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kworks", "0002_alter_kwork_price_minor_kworkfaq_kworkimage_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kwork",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Qoralama"),
                    ("active", "Aktiv"),
                    ("paused", "Pauzada"),
                    ("deleted", "O'chirilgan"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
