# Generated by Django 5.2.15 on 2026-06-14 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_minor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], default='new', max_length=24),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='message_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.ordermessage')),
            ],
            options={
                'verbose_name': 'Message Attachment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('accepted', 'Accepted'), ('delivered', 'Delivered'), ('revision_requested', 'Revision Requested'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('disputed', 'Disputed')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer_text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='order_requirements/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requirements', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Requirement',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('canceled', 'Canceled')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_requests', to='orders.delivery')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='orders.order')),
            ],
            options={
                'verbose_name': 'Revision Request',
                'ordering': ['-created_at'],
            },
        ),
    ]
