# Generated by Django 5.2.15 on 2026-06-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordermessage_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='order_requirements/'),
        ),
        migrations.DeleteModel(
            name='OrderRequirement',
        ),
    ]
