# Generated to safely align notification models with TimeStampedUUIDModel.

import uuid

from django.db import migrations, models


UUID_SQL = """
CREATE EXTENSION IF NOT EXISTS pgcrypto;
ALTER TABLE {table} DROP COLUMN id CASCADE;
ALTER TABLE {table} ADD COLUMN id uuid PRIMARY KEY DEFAULT gen_random_uuid();
"""

REVERSE_UUID_SQL = """
ALTER TABLE {table} DROP COLUMN id CASCADE;
ALTER TABLE {table} ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=UUID_SQL.format(table='"notifications_notificationpreference"'),
            reverse_sql=REVERSE_UUID_SQL.format(table='"notifications_notificationpreference"'),
            state_operations=[
                migrations.AlterField(
                    model_name="notificationpreference",
                    name="id",
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.RunSQL(
            sql=UUID_SQL.format(table='"notifications_devicetoken"'),
            reverse_sql=REVERSE_UUID_SQL.format(table='"notifications_devicetoken"'),
            state_operations=[
                migrations.AlterField(
                    model_name="devicetoken",
                    name="id",
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.RunSQL(
            sql=UUID_SQL.format(table='"notifications_notification"'),
            reverse_sql=REVERSE_UUID_SQL.format(table='"notifications_notification"'),
            state_operations=[
                migrations.AlterField(
                    model_name="notification",
                    name="id",
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
